### ISSUE TITLE
Change required on the Plasma Discover Wudgets Page required

### ISSUE THREAD

**Issue by BristolPiggy** [korapp/plasma-cloudflare-warp#3]
On the "Plasma Widgets - Discover" page, under the requirements section, the first point is "NordVPN Linux Client".

This confused me somewhat as I have never used NordVPN in my dealings with Cloudflare. Upon further investigation, I believe it should read "Cloudflare Warp Linux Client" or something similar to that effect.

[A side note:
As yet I am not sure whether this can be Cloudflare's free Warp Client (making all DNS requests to Cloudflare's 1.1.1.1 service) or whether it needs to be the Warp Client provided along with the Warp Tunnels software, or an either/ or situation. If the later, it may go some way towards improving Cloudflare Tunnels implementation, as so far creating insecure access is easy, securing them however is another matter!]

**Comment by korapp** [comment]
Thanks
