### ISSUE TITLE
No additional information displayed

### ISSUE THREAD

**Issue by gerald-drissner** [korapp/plasma-cloudflare-warp#7]
On Plasma 5.27.10, the plasmoid works, but it does not show any additional information (endpoints, time to last handshake, estimated loss etc.). But I also do not get any error message.

**Comment by korapp** [comment]
Could you provide the version of the plasmoid, warp-cli and check if anything useful can be found the in logs?
`journalctl _COMM=plasmashell --grep com.github.korapp.cloudflare-warp`

**Comment by gerald-drissner** [comment]
Sure! I previously had Plasma 5.27.10 (x-org!), and it did not show any details. Now, I have switched to wayland (without changing anything on the setup; just new login) and it works!!! So it was related to x-org.
