### ISSUE TITLE
Feature request: signaling icon when disconnected

### ISSUE THREAD

**Issue by wildwaffle** [korapp/plasma-cloudflare-warp#8]
Now the icon fits perfectly into the Plasma style. But that is precisely why its status is sometimes not obvious. For example, in a dark theme it is a light gray cloud (connected) or just gray (disconnected).

However, if Warp is for security, perhaps a brighter icon would be appropriate. For example, if there is no Warp connection, there might be a bright red warning cloud. Or regular gray, but with a bright exclamation mark.

Even if this were implemented in an extremely simple way, for example, as the ability to enter your own color values ​​into a text config (#FF0000 for red), this would be a big plus.

**Comment by korapp** [comment]
How about optionally using the negativeTextColor from the current theme?
In most cases it will be reddish but matching the palette = no need to adjust it when changing the theme.
